### PR TITLE
restruct python wrapper

### PR DESCRIPTION
**Pull request by zhizhongzhiwai**
restruct python wrapper for better practice

1: move wrapper/python/pytest to wrapper/python/tests
exec pytest pytest return error with naming conflict. fix it!

2: cython_tests.sh can be executed without beware working directory.

3:move LIBDOGECOIN_API to separate python pxd file, invoid name conflict.
example: it's ok to call libdogecoin.libdogecoin.context_start()  instead of libdogecoin.libdogecoin.w_context_start()

### CODE REVIEW

**Comment by edtubbs** [comment]
Thanks for your contribution!  I'll review and test these changes today.

**Comment by edtubbs** [comment]
```
===================== test session starts ======================
platform linux -- Python 3.6.9, pytest-7.0.1, pluggy-1.0.0 -- /home/ed/libdogecoin/wrappers/python/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/ed/libdogecoin/wrappers/python
collected 48 items

../tests/address_test.py::TestAddressFunctions::test_derived_hd_pubkey_gen_mainnet PASSED [  2%]
../tests/address_test.py::TestAddressFunctions::test_derived_hd_pubkey_gen_testnet PASSED [  4%]
../tests/address_test.py::TestAddressFunctions::test_derived_keypair_is_valid_mainnet PASSED [  6%]
../tests/address_test.py::TestAddressFunctions::test_derived_keypair_is_valid_testnet PASSED [  8%]
../tests/address_test.py::TestAddressFunctions::test_derived_p2pkh_addr_format_is_valid_mainnet PASSED [ 10%]
../tests/address_test.py::TestAddressFunctions::test_derived_p2pkh_addr_format_is_valid_testnet PASSED [ 12%]
../tests/address_test.py::TestAddressFunctions::test_keypair_is_valid_mainnet PASSED [ 14%]
../tests/address_test.py::TestAddressFunctions::test_keypair_is_valid_testnet PASSED [ 16%]
../tests/address_test.py::TestAddressFunctions::test_master_keypair_is_valid_mainnet PASSED [ 18%]
../tests/address_test.py::TestAddressFunctions::test_master_keypair_is_valid_testnet PASSED [ 20%]
../tests/address_test.py::TestAddressFunctions::test_master_p2pkh_addr_format_is_valid_mainnet PASSED [ 22%]
../tests/address_test.py::TestAddressFunctions::test_master_p2pkh_addr_format_is_valid_testnet PASSED [ 25%]
../tests/address_test.py::TestAddressFunctions::test_master_privkey_gen_mainnet PASSED [ 27%]
../tests/address_test.py::TestAddressFunctions::test_master_privkey_gen_testnet PASSED [ 29%]
../tests/address_test.py::TestAddressFunctions::test_master_pubkey_gen_mainnet PASSED [ 31%]
../tests/address_test.py::TestAddressFunctions::test_master_pubkey_gen_testnet PASSED [ 33%]
../tests/address_test.py::TestAddressFunctions::test_p2pkh_addr_format_is_valid_mainnet PASSED [ 35%]
../tests/address_test.py::TestAddressFunctions::test_p2pkh_addr_format_is_valid_testnet PASSED [ 37%]
../tests/address_test.py::TestAddressFunctions::test_privkey_gen_mainnet PASSED [ 39%]
../tests/address_test.py::TestAddressFunctions::test_privkey_gen_testnet PASSED [ 41%]
../tests/address_test.py::TestAddressFunctions::test_pubkey_gen_mainnet PASSED [ 43%]
../tests/address_test.py::TestAddressFunctions::test_pubkey_gen_testnet PASSED [ 45%]
../tests/mnemonic_test.py::TestMnemonic::test_generateEnglishMnemonic PASSED [ 47%]
../tests/mnemonic_test.py::TestMnemonic::test_generateRandomEnglishMnemonic PASSED [ 50%]
../tests/transaction_test.py::TestTransactionFunctions::test_add_double_utxo_value PASSED [ 52%]
../tests/transaction_test.py::TestTransactionFunctions::test_add_output PASSED [ 54%]
../tests/transaction_test.py::TestTransactionFunctions::test_add_output_bad_index PASSED [ 56%]
../tests/transaction_test.py::TestTransactionFunctions::test_add_output_value PASSED [ 58%]
../tests/transaction_test.py::TestTransactionFunctions::test_add_single_utxo_value PASSED [ 60%]
../tests/transaction_test.py::TestTransactionFunctions::test_add_utxo PASSED [ 62%]
../tests/transaction_test.py::TestTransactionFunctions::test_add_utxo_bad_index PASSED [ 64%]
../tests/transaction_test.py::TestTransactionFunctions::test_clear_transaction PASSED [ 66%]
../tests/transaction_test.py::TestTransactionFunctions::test_finalize_transaction PASSED [ 68%]
../tests/transaction_test.py::TestTransactionFunctions::test_full_decimal_amt_transaction_build PASSED [ 70%]
../tests/transaction_test.py::TestTransactionFunctions::test_full_int_amt_transaction_build PASSED [ 72%]
../tests/transaction_test.py::TestTransactionFunctions::test_get_raw_transaction PASSED [ 75%]
../tests/transaction_test.py::TestTransactionFunctions::test_get_raw_transaction_bad_index PASSED [ 77%]
../tests/transaction_test.py::TestTransactionFunctions::test_sign_raw_transaction PASSED [ 79%]
../tests/transaction_test.py::TestTransactionFunctions::test_sign_raw_transaction_bad_privkey PASSED [ 81%]
../tests/transaction_test.py::TestTransactionFunctions::test_sign_raw_transaction_high_send_amt PASSED [ 83%]
../tests/transaction_test.py::TestTransactionFunctions::test_sign_transaction PASSED [ 85%]
../tests/transaction_test.py::TestTransactionFunctions::test_sign_transaction_value PASSED [ 87%]
../tests/transaction_test.py::TestTransactionFunctions::test_start_transaction PASSED [ 89%]
../tests/transaction_test.py::TestTransactionFunctions::test_start_transaction_value PASSED [ 91%]
../tests/transaction_test.py::TestTransactionFunctions::test_store_long_raw_transaction PASSED [ 93%]
../tests/transaction_test.py::TestTransactionFunctions::test_store_raw_transaction PASSED [ 95%]
../tests/transaction_test.py::TestTransactionFunctions::test_store_raw_transaction_value PASSED [ 97%]
../tests/wow_test.py::TestWow::test_wow PASSED           [100%]

====================== 48 passed in 0.61s ======================
```
```
ed@localhost:~$ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           3
Vendor ID:           Qualcomm
Model:               14
Stepping:            0xd
CPU max MHz:         2841.6001
CPU min MHz:         300.0000
BogoMIPS:            38.40
L1d cache:           unknown size
L1i cache:           unknown size
L2 cache:            unknown size
L3 cache:            unknown size
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
```
```
ed@localhost:~/libdogecoin$ make check
make[1]: Entering directory '/home/ed/libdogecoin'
make  check-TESTS
make[2]: Entering directory '/home/ed/libdogecoin'
PASSED - test_address()
PASSED - test_aes()
PASSED - test_base58()
PASSED - test_base64()
PASSED - test_bip32()
PASSED - test_bip39()
PASSED - test_bip44()
PASSED - test_block_header()
PASSED - test_buffer()
PASSED - test_cstr()
PASSED - test_ecc()
PASSED - test_hash()
PASSED - test_key()
PASSED - test_koinu()
PASSED - test_memory()
PASSED - test_moon()
PASSED - test_op_return()
PASSED - test_random()
PASSED - test_rmd160()
PASSED - test_serialize()
PASSED - test_sha_256()
PASSED - test_sha_512()
PASSED - test_sha_hmac()
PASSED - test_signmsg()
PASSED - test_signmsg_ext()
PASSED - test_transaction()
PASSED - test_tx_serialization()
PASSED - test_invalid_tx_deser()
PASSED - test_tx_sign()
PASSED - test_tx_sighash()
PASSED - test_tx_sighash_ext()
PASSED - test_tx_negative_version()
PASSED - test_scripts()
PASSED - test_script_parse()
PASSED - test_script_op_codeseperator()
PASSED - test_utils()
PASSED - test_vector()
qrcode generation - Using test addr:    D8yapy4hPo7MpbMP2fhUHZ9fnRCjXkKUMS
Print function:
                                                                
                                                                
                                                                
                                                                
        ##############      ####      ####      ##  ##############
        ##          ##  ##  ##    ####  ##  ##      ##          ##
        ##  ######  ##  ########  ##  ##      ##    ##  ######  ##
        ##  ######  ##  ##              ####  ##    ##  ######  ##
        ##  ######  ##      ######    ####  ##  ##  ##  ######  ##
        ##          ##    ##  ##      ##  ##        ##          ##
        ##############  ##  ##  ##  ##  ##  ##  ##  ##############
                        ######      ######  ##                  
        ##          ##  ##      ##        ##  ##  ####    ######
            ######      ####      ##    ######    ##  ####  ##  
        ##  ##    ########  ##  ############    ####  ######    
          ####        ######  ##  ##  ##    ##  ##    ##  ##  ##
        ####  ##    ##      ##  ####  ##  ##  ##    ######    ##
        ##  ##        ####      ##      ##      ##  ######    ####
          ######  ######  ##  ##      ########    ##  ##        
                ####  ########  ##          ##  ##    ########  ##
        ####  ########  ########              ##      ##  ########
        ######  ####  ##        ######  ##  ######      ##  ######
        ##########  ##  ##  ######    ##    ######          ######
        ##      ####  ####        ##    ##    ######  ##        
        ##      ##  ##  ##    ##    ########    ##############  
                        ####  ####  ##    ####  ##      ######  ##
        ##############        ##      ############  ##  ##      
        ##          ##    ##    ##  ####    ######      ####    ##
        ##  ######  ##      ##########  ####  ##############  ####
        ##  ######  ##    ##  ##  ####  ####    ####        ##  ##
        ##  ######  ##    ##  ######  ####  ##        ####    ##
        ##          ##      ##      ######  ####    ##  ######  ##
        ##############  ####        ##    ##      ##    ####    
                                                                
                                                                
                                                                
                                                                

String function:
                                                                
                                                                
                                                                
                                                                
        ##############      ####      ####      ##  ##############
        ##          ##  ##  ##    ####  ##  ##      ##          ##
        ##  ######  ##  ########  ##  ##      ##    ##  ######  ##
        ##  ######  ##  ##              ####  ##    ##  ######  ##
        ##  ######  ##      ######    ####  ##  ##  ##  ######  ##
        ##          ##    ##  ##      ##  ##        ##          ##
        ##############  ##  ##  ##  ##  ##  ##  ##  ##############
                        ######      ######  ##                  
        ##          ##  ##      ##        ##  ##  ####    ######
            ######      ####      ##    ######    ##  ####  ##  
        ##  ##    ########  ##  ############    ####  ######    
          ####        ######  ##  ##  ##    ##  ##    ##  ##  ##
        ####  ##    ##      ##  ####  ##  ##  ##    ######    ##
        ##  ##        ####      ##      ##      ##  ######    ####
          ######  ######  ##  ##      ########    ##  ##        
                ####  ########  ##          ##  ##    ########  ##
        ####  ########  ########              ##      ##  ########
        ######  ####  ##        ######  ##  ######      ##  ######
        ##########  ##  ##  ######    ##    ######          ######
        ##      ####  ####        ##    ##    ######  ##        
        ##      ##  ##  ##    ##    ########    ##############  
                        ####  ####  ##    ####  ##      ######  ##
        ##############        ##      ############  ##  ##      
        ##          ##    ##    ##  ####    ######      ####    ##
        ##  ######  ##      ##########  ####  ##############  ####
        ##  ######  ##    ##  ##  ####  ####    ####        ##  ##
        ##  ######  ##    ##  ######  ####  ##        ####    ##
        ##          ##      ##      ######  ####    ##  ######  ##
        ##############  ####        ##    ##      ##    ####    
                                                                
                                                                
                                                                
                                                                

Attempting to write PNG...
Attempting to write JPG...
PASSED - test_qr()
info=  key=2036689762  l->key=NULL  r->key=NULL  p->key=NULL  red=0
PASSED - test_red_black_tree()
PASSED - test_logdb_memdb()
PASSED - test_logdb_rbtree()
PASSED - test_examples()
PASSED - test_wallet_basics()
PASSED - test_wallet()
ext key:             dgpv51eADS3spNJh95YDAnF3TpFuNjfm85FVK3HDftwaiQPcRBN2f2mTewwbdPAMHMiq9FkaMyFhNbxSPfAZUXvPzx7iZiLfzYNx8tTzGVq7AYg
extended pubkey:     dgub8kXBZ7ymNWy2RwCND1s1afoVqJ3PxCHCbe4Rq1LZWXScyEUj4oKEJFMFCatzVhqK1shhKA5u3CQNQaNxwSqVXcwr146GrXEASWpDjN7c7br
pubkey hex:          0245159e5d455b5b5f132f2a1cc2da9fa435d50d4f8657f008183b5654acd3c14e
privatekey WIF:      QWCeoCEhap9TWkaVXKtVEEekac6miqsip6wXhpKScAzVesRL7Atc
depth:               0
child index:         0
p2pkh address:       DLmHWzekecjLF3gyhAhhFKQNNpVytJbtQy
PASSED - test_tool()
PASSED - test_net_flag_defined()
PASSED - test_net_basics_plus_download_block()
PASSED - test_protocol()
Discover peers...done
Start interacting with the p2p network...
PASSED - test_spv()
PASS: tests
=============
1 test passed
=============
make[2]: Leaving directory '/home/ed/libdogecoin'
make[1]: Leaving directory '/home/ed/libdogecoin'
```

**Comment by xanimo** [comment]
This looks good but we are planning on decoupling/removing the wrappers directory from the project soon. For a better place to add changes re mnemonics test, et al. I would suggest opening a similar PR against https://github.com/dogeorg/python-libdogecoin/tree/main with the caveat that you don't remove the w_ prefix or any breaking changes.

It's set up a bit different than the way this wrapper remnant is as it wraps only publicly released binaries which as of last update was 0.1.0 so there is definitely some work to do regarding updating sha256 checksums and release versions there in the fetch.py script.

I am thrilled to have someone with active interest in contributing to the python wrapper but it's new home is the url above.

Outside all that, I'd say from a technical perspective, this works but it is a breaking change relative to the removal of w_ prefix so with that I'd say this needs some changes but with the memory that the wrappers dir will eventually be removed.

**Comment by zhizhongzhiwai** [comment]
Take wow.h: LIBDOGECOIN_API void wow() as an example
The w_ prefix prevents python interface functions from overriding cython function names.
```
def w_wow(): 
    wow()
```
But when the cython wrapper of wow.h is separated into a single file _wow.pxd, the wrapper for the wow function becomes:
```
from . cimport _wow
def wow():
    _wow.wow()
```
 call the wow function use libdogecoin.wow instead of the libdogecoin.w_wow,  is more intuitive and consistent with libdogecion api name. :->  , this is just my personal opinion.

As more APIs are added, it is easier to organize by splitting them into different declaration files _foo.pxd

i'll try  dogeorg/python-libdogecoin

**Pull request closed without merging**
