### PR TITLE
fix DragonFlyBSD 6.4-RELEASE support

### PR DESCRIPTION
**Pull request by movepointsolutions**
it has endianness-related functions named the same

### CODE REVIEW

**Comment by movepointsolutions** [comment]
I can't verify if previous versions of DFLY were ok with the FreeBSD code branch
So it could probably break support for older dragonflies

**Comment by movepointsolutions** [comment]
Please don't merge this commit, I'll come back with exact dfly version check

**Comment by movepointsolutions** [comment]
Whatever, I'm not that proficient in git

> Please don't merge this commit, I'll come back with exact dfly version check

**Comment by movepointsolutions** [comment]
To be precise,
/usr/include/sys/param.h:#define __DragonFly_version 600400	/* propagated to newvers */

**Comment by xanimo** [comment]
going to explore this after we release 0.1.3. thanks!

**Review by xanimo — APPROVED** [review]
I finally have a working environment to test this but I see what you mean:

dogecoinfoundation/0.1.4-dev:
image

your branch:
image

ACK

**Comment by xanimo** [comment]
Including a [demo](https://gist.github.com/xanimo/85970d3baffd1b34994379a6432601ea) just in case anyone else wants to test DragonFly BSD on linux. I would skip ahead from 6.4 to their daily snapshots as noted in the comment underneath the main gist. Also I would manually download and install libunistring and libevent and copy files from `/usr/local/include` to `libdogecoin/include/` as we can't use `make -C depends` due to incompatible line breaks.

**Comment by movepointsolutions** [comment]
Very glad to see that you support D-flies)

**Review by michilumin — APPROVED** [review]
-to me- looks like passive/non issue causing additions so I'm OK with it.

**Comment by michilumin** [comment]
> Whatever, I'm not that proficient in git
> 
> > Please don't merge this commit, I'll come back with exact dfly version check

that's ok.  nobody is.

**Pull request merged**
