### PR TITLE
lib: added key string constants, chainparams and bip32/44 wrappers

### PR DESCRIPTION
**Pull request by edtubbs**
address: added depth to dogecoin_hd_generate_key for extended keys
chainparams: added isTestnetFromB58Prefix and isMainnetFromB58Prefix wrappers
bip32: added wrappers and depth to dogecoin_hd_generate_key for extended keys
bip39: moved constant to header
bip44: added wrappers and updated to derive_bip44_extended_key
key: added wrappers
dogecoin: added key string and script constants
example: moved constants to header, updated for key string constants, indentation and to derive_bip44_extended_key
tool: added wrappers, assert for dogecoin_pubkey_get_hex call and depth to dogecoin_hd_generate_key for extended keys
tx: added wrapper
vector: added wrappers for serialization/deserialization
test: added wrappers to bip32, key, transaction, tool, and vector tests

### CODE REVIEW

**Comment by edtubbs** [comment]
Tested on x86 windows, linux and aarch64 linux.

**Comment by edtubbs** [comment]
Retested examples on x86 windows, linux and aarch64 linux.

**Comment by edtubbs** [comment]
Retested example with correct result.

**Comment by edtubbs** [comment]
Retested with update to tool_test.

**Comment by xanimo** [comment]
one thing i just noticed with regards to the tool test is there are no guards per hardening within `hd_derive`. i'm wondering if this should return an error prompt if a user passes ' or h? for instance, adding a ' or h:
```
    size_t extoutsize = 200;
    char* extout=dogecoin_char_vla(extoutsize);
    const char* privkey = "dgpv557t1z21sLCnAz3cJPW5DiVErXdAi7iWpSJwBBaeN87umwje8LuTKREPTYPTNGXGnB3oNd2z6RmFFDU99WKbiRDJKKXfHxf48puZibauJYB";
    debug_print("\nMaster private key:  %s\n", privkey);

    u_assert_int_eq(hd_derive(&dogecoin_chainparams_main, privkey, "m/0h", extout, extoutsize), true);
    // u_assert_str_eq(extout, "dgpv55wVA8mg2HkLPXa4bSyi83hbXrwVWsiTE2Z3kSTUtC6QUyg3ed3FprcvAFKWUSvyRtaPuVwfbcQMQqVXM12yrxQtSCB2iPF4A6RdDp53jjy");
    printNode(false, extout);
```
yields an overflow here:
```
ext key:             dgpv55wVA8mpMxHJbEck3FctD5WKCUMRHgDqmcDLkVodsuN4846ZmSFRpuvWjg1E4w1RwkxxRHJPgpspN64AHaWzcQU5QQDjBTFZHCA9ttGNEBT
extended pubkey:     dgub8ppWVphhv6wdt6Gu5VErKw3uf2j47oFZ4CzYucCcg2R4g7DGBCoCUDLAJvJSAutDfVETaiWDaGJvgEDKawWRCkBAU2MTmZ8K83JNaBoFbhb
pubkey hex:          03888018e1c71a8fa3be86f3e5536c7dfa5916a983ef2c7c3f1076d751125ec571
privatekey WIF:      QVjay8K1ktSjCEoHRq3oftCRT1pqtGDgWuGe3AF8ZAAwaAAbnpKJ
depth:               2
child index:         -2147483648
p2pkh address:       DNMeGu5X8ptm9hFETMEswHbV8QjnAFKBRe
```
*this isn't a blocker per this pr but just wanted to note.*

**Review by xanimo — APPROVED** [review]
ACK, built and tested on x86_64-pc-linux-gnu.

**Review by michilumin — APPROVED** [review]
big PR but much of that i know is whitespace/tab deletion, lgtm though.

**Pull request merged**
