### PR TITLE
[WIP] ci: Add Android support

### PR DESCRIPTION
**Pull request by alamshafil**
This PR adds Android support to the CI system. macOS SDK has been renamed from "SDK" to "MAC_SDK" to make a distinction between macOS SDK and Android NDK. 

So far this PR does not test the Android binaries since I am not sure how to download the needed Android libraries.

### CODE REVIEW

**Comment by xanimo** [comment]
this looks great alam!

**Comment by edtubbs** [comment]
Looking into updating `Test libdogecoin` in `ci.yml` to test the aarch64-android binaries; I'll keep you posted.  Thanks @alamshafil!

**Comment by edtubbs** [comment]
@alamshafil I've added a ci test for the aarch64-android target. Can you try and set up the test environment? 
 https://github.com/edtubbs/libdogecoin/commit/8e3d6fa093727e757d21e329f8dd122de39931cb#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR274 Note the branch name must start with 0.1.3-dev for the ci to run.

**Comment by xanimo** [comment]
noting again that this has been merged in #192

**Pull request closed without merging**
