### PR TITLE
cmake: added build type for msvc

### PR DESCRIPTION
**Pull request by edtubbs**
Added `--config ${CMAKE_BUILD_TYPE}` to the `cmake --build` command to specify the build type for msvc.

### CODE REVIEW

**Comment by edtubbs** [comment]
Updates were made to support `Release` mode builds, including the use of `assert` and disabling the `USE_TPM2` flag.

**Review by michilumin — APPROVED** [review]
Ok I THINK i followed all your logic transitions here... and they were correct. I'm pretty sure.

**Comment by edtubbs** [comment]
TPM2 tests now successfully pass in `Release` mode.

**Review by xanimo — APPROVED** [review]
ACK. tested and built in .git repo and gitian .zip.

**Review by michilumin — APPROVED** [review]
ACK on tpm fixes

**Pull request merged**
